config/routes.rb
PersoSite::Application.routes.draw do
  match "/home(/:rubric)" => "pages#home"
  match '/magic',   :to => 'pages#magic'
  match '/contact',    :to => 'pages#contact'
  match '/news',   :to => 'pages#news'

  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@activeButton = "about"
  	@rubric = params[:rubric]
  	if @rubric.nil?
  		@rubric = "project"
  	end
  end

  def magic
  	@activeButton = "magic"
  end

  def news
	@activeButton = "news"
  end

  def contact
  	@activeButton = "contact"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(buttonName)
		if @activeButton.nil?
			false
		else
			@activeButton == buttonName
		end
	end

	def menuBarButtonClass(buttonName)
		if active? buttonName
			'class=active'
		else
			""
		end
	end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<hr>
<footer>
	<p>Dispatch Project - &copy; Brown Institute, Magic Grant 2012</p>
</footer>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dispatch", root_path, :class => "brand"%>
      <div class="nav-collapse collapse">
        <ul class="nav">
          <li <%= menuBarButtonClass "about" %> ><%= link_to "About", root_path%></li>
          <li <%= menuBarButtonClass "magic" %> ><%= link_to "Magic Grant", magic_path%></li>
          <li <%= menuBarButtonClass "news" %> ><%= link_to "News", news_path%></li>
          <li <%= menuBarButtonClass "contact" %> ><%= link_to "Contact", contact_path%></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag 'twitter_bootstrap/bootstrap.min.css', :media => 'screen' %>
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

<%= javascript_include_tag "jquery-1.7.2.min.js" %>
<%= javascript_include_tag "caroussel.js" %>

<!-- Le styles -->
<style type="text/css">
  body {
    padding-top: 60px;
    padding-bottom: 40px;
  }
</style>

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Le fav and touch icons -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Dispatch</title>
    <%= csrf_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= render 'layouts/stylesheets' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">

      <%= yield %>
      
      <%= render 'layouts/footer' %>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- <script src="../assets/js/jquery.js"></script>
    <script src="../assets/js/bootstrap-transition.js"></script>
    <script src="../assets/js/bootstrap-alert.js"></script>
    <script src="../assets/js/bootstrap-modal.js"></script>
    <script src="../assets/js/bootstrap-dropdown.js"></script>
    <script src="../assets/js/bootstrap-scrollspy.js"></script>
    <script src="../assets/js/bootstrap-tab.js"></script>
    <script src="../assets/js/bootstrap-tooltip.js"></script>
    <script src="../assets/js/bootstrap-popover.js"></script>
    <script src="../assets/js/bootstrap-button.js"></script>
    <script src="../assets/js/bootstrap-collapse.js"></script>
    <script src="../assets/js/bootstrap-carousel.js"></script>
    <script src="../assets/js/bootstrap-typeahead.js"></script> -->

  </body>
</html>

app/views/pages/_homeDownColumns.html.erb
<!-- Example row of columns -->
<div class="row">
  <div class="span4">
    <h2>The Project</h2>
     <p>Dispatch is a publishing tool for citizen journalists in conflict areas, with an emphasis on usability and security.</p>
    <p><a class="btn btn-primary" href="/dispatch/home/project">Learn more &raquo;</a></p>
  </div>
  <div class="span4">
    <h2>Progress</h2>
     <p>Here we present our milestones and the progress of our project with a summary of the results.</p>
    <p><a class="btn btn-info" href="/dispatch/home/progress">Learn more &raquo;</a></p>
 </div>
  <div class="span4">
    <h2>The Team</h2>
    <p>We are a mixed team of Journalists and CS students and faculty, from Stanford and Columbia Universities.</p>
    <p><a class="btn btn-success" href="/dispatch/home/team">Learn more &raquo;</a></p>
  </div>
</div>

app/views/pages/_homeProgress.html.erb
<h2>Project Progress</h2>

<table class="table table-striped">
	<thead>
	  <tr>
	    <th>Milestone</th>
	    <th>Description</th>
	    <th>Progress</th>
	  </tr>
	</thead>
	<tbody>
	  <tr>
	    <td>September 2012</td>
	    <td>Milestone 0: application for secure communications on Android & iPhone (Musubi)</td>
	    <td>Android on the Android Market, iOS version being built</td>
	  </tr>
	  <tr>
	    <td>November 2012</td>
	    <td>Test secure communication between student reporters and publication on Tumblr on election night</td>
	    <td>TODO</td>
	  </tr>
	  <tr>
	    <td>February 2013</td>
	    <td>Identify news agencies for a field test</td>
	    <td>TODO</td>
	  </tr>
	  <tr>
	    <td>June 2013</td>
	    <td>Sneakernet: disconnection resistance on Android</td>
	    <td>TODO</td>
	  </tr>
	  <tr>
	    <td>June-Sept. 2013</td>
	    <td>Field tests with news agencies</td>
	    <td>TODO</td>
	  </tr>
	</tbody>
	</table>

app/views/pages/_homeProject.html.erb
<h2>The Dispatch Project</h2>
<br>
	<div id="myCarousel" class="carousel slide">

	    <div class="carousel-inner">
	      <div class="item">
	      	<%= image_tag("sneakernet.png", :style => "display: block; margin-left: auto; margin-right: auto;display: block; ") %>
	        <div class="carousel-caption">
	          <h4>Speak Up</h4>
	          <p>We are building a "sneakernet" to allow people to avoid censorship, from internet restrictions to device confiscation.</p>
	        </div>
	      </div>
	      <div class="item">
	      	<%= image_tag("SecureCom.png", :style => "display: block; margin-left: auto; margin-right: auto;display: block; ") %>
	        <div class="carousel-caption">
	          <h4>Secure Source-Journalist Communication</h4>
	          <p>Dispatch offers secure communication between sources and journalists. In addition, to help with source protection, it gives trusted virtual identities to journalists to be recognized, and for sources to build trust.</p>
	        </div>
	      </div>
	      <div class="item">
	      	<%= image_tag("publish.png", :style => "display: block; margin-left: auto; margin-right: auto;display: block; ") %>
	        <div class="carousel-caption">
	          <h4>Publish</h4>
	          <p>From Dispatch, you can publish on different media platforms directly or after editotial review.</p>
	        </div>
	      </div>
	      <div class="item active">
	      	<%= image_tag("time.jpg", :style => "display: block; margin-left: auto; margin-right: auto;display: block; ") %>
	        <div class="carousel-caption">
	          <h4>What is Dispatch?</h4>
	          <p>Dispatch is a publishing tool for citizen journalists in conflict areas.</p>
	        </div>
	      </div>
	    </div>
	    <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
	    <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
</div>

app/views/pages/_homeTeam.html.erb
<ul class="thumbnails">
  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "kanak.jpeg"), "http://stanford.edu/~kanak" %>
      <h5 style="text-align: center; margin-top: 0px;">Kanak Biscuitwala</h5>
    </div>
  </li>
  </li>
  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "mathias.png"), "http://mathias.lecuyer.me" %>
      <h5 style="text-align: center; margin-top: 0px;">Mathias Lécuyer</h5>
    </div>
  </li>
  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "TJ.jpg"), "https://plus.google.com/118248804586039445285/posts" %>
      <h5 style="text-align: center; margin-top: 0px;">T.J. Purtell</h5>
    </div>
  </li>
  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "susan.png"), "http://www.journalism.columbia.edu/profile/365-susan-e-mcgregor/10" %>
      <h5 style="text-align: center; margin-top: 0px;">Susan McGregor</h5>
    </div>
  </li>
  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "augustin.jpg"), "http://www.cs.columbia.edu/~augustin/" %>
      <h5 style="text-align: center; margin-top: 0px;">Augustin Chaintreau</h5>
    </div>
  </li>

  <li class="span8">
    <div class="thumbnail">
      <h2>The Dispatch Team</h2>
      <p>We are a mixed team of journalists and computer scientists from Columbia and Stanford University, also working with Tumblr as a publishing platform. We are currently looking for a strong journalism student to join our team as soon as possible; the role transitions into a full-time paid position for Spring-Summer 2013.<br /><br />
	  The students are:<br></p>
		<dl class="dl-horizontal">
		<DT>Kanak Biscuitwala
		<DD>CS - Stanford
		<DT>Mathias Lécuyer
		<DD>CS - Columbia
		<DT>T.J. Purtell
		<DD>CS - Stanford
		<DT>Journalism Student
		<DD>Journalism - Columbia (yet to be determined)
		</dl>
	  <p>Advised by:<br></p></p>
		<dl class="dl-horizontal">
		<DT>Susan McGregor
		<DD>Journalism school - Columbia
		<DT>Monica Lam
		<DD>CS - Stanford
		<DT>Augustin Chaintreau
		<DD>CS - Columbia
		<DT>Chris Haseman
		<DD>Tumblr
		</dl>
	  <p>You can click on the pictures to see each member's personal website.<br> </p>
    </div>

  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "monica-lam.jpg"), "http://suif.stanford.edu/~lam/" %>
      <h5 style="text-align: center; margin-top: 0px;">Monica Lam</h5>
    </div>
  </li>
  <li class="span2">
    <div class="thumbnail">
      <%= link_to (image_tag "chris.png"), "http://haseman.tumblr.com/" %>
      <h5 style="text-align: center; margin-top: 0px;">Chris Haseman</h5>
    </div>
  </li>
</ul>

app/views/pages/contact.html.erb
<div class="hero-unit">
	<h2>Contact Information</h2>

	<dl class="dl-horizontal">
		<DT>Email
		<DD> dispatch < at > lists.cs.columbia < dot > edu
	</dl>

</div>

app/views/pages/home.html.erb
<!-- Main hero unit for a primary marketing message or call to action -->
<div class="hero-unit">

	<%= if @rubric == 'project'
	    	render 'homeProject'
	    elsif @rubric == 'progress'
	    	render 'homeProgress'
	    elsif @rubric == 'team'
	    	render 'homeTeam'
	    end
	%>
</div>

<!-- Example row of columns -->
<%= render 'pages/homeDownColumns' %>

app/views/pages/magic.html.erb
<div class="hero-unit">
	<h2>Brown Institute</h2>
	<p>Learn more about the Brown Institute for Media Innovation <%= link_to "here", 'http://brown.stanford.edu/full/index.html'%>. <br><br> </p>

	<h2>Magic Grant</h2>
	<p>Every year, the Brown Institute supports a few projects for Media innovation through the <%= link_to "Magic Grant", 'http://brown.stanford.edu/full/magic_grants.html'%>.</p>
</div>

app/views/pages/news.html.erb
<div class="hero-unit">
	<h1>Dispatch News</h1> <br /><br />
	<h2>Dispatch at the ONA12 Midway</h2>
	<p>The Dispatch team attended the <%= link_to "2012 Online News Association Conference", 'http://ona12.journalists.org'%> in San Francisco to kick off the project, as well as learn from and network with attending journalists.</p>
	<p>More information is available <%= link_to "here", 'http://themidway.tumblr.com/post/31991527851/dispatch-offers-secure-mobile-publishing'%>. <br><br> </p>
</div>